import os, sys, gi
gi.require_version('Gtk','3.0')
from gi.repository import Gtk, Gdk
label, dest = sys.argv[1:]
window=Gtk.Window(title=label)
window.set_wmclass(label,label)
window.set_default_size(600,350)
box=Gtk.Box(orientation=Gtk.Orientation.VERTICAL,spacing=20)
box.pack_start(Gtk.Label(label=label),False,False,20)
entry=Gtk.Entry()
entry.connect('populate-popup',lambda e, menu: open(dest+'.popup','w').write('opened'))
entry.connect('changed',lambda e: open(dest,'w').write(e.get_text()))
box.pack_start(entry,False,False,20)
button=Gtk.Button(label='Click to record pointer input')
button.connect('clicked',lambda b: open(dest+'.click','a').write('click\n'))
box.pack_start(button,False,False,20)
source=Gtk.Button(label='Drag this payload')
source.drag_source_set(Gdk.ModifierType.BUTTON1_MASK, [Gtk.TargetEntry.new('text/plain', 0, 0)], Gdk.DragAction.COPY)
source.connect('drag-begin', lambda w,c: open(dest+'.drag','w').write('begin'))
source.connect('drag-data-get', lambda w,c,data,info,time: data.set_text(label+'-payload', -1))
box.pack_start(source,False,False,20)
target=Gtk.Button(label='Drop payload here')
target.drag_dest_set(Gtk.DestDefaults.ALL, [Gtk.TargetEntry.new('text/plain', 0, 0)], Gdk.DragAction.COPY)
def received(w,c,x,y,data,info,time):
    open(dest+'.drop','w').write(data.get_text())
    Gtk.drag_finish(c,True,False,time)
target.connect('drag-data-received', received)
box.pack_start(target,False,False,20)
window.add(box)
window.connect('destroy',Gtk.main_quit)
window.show_all()
entry.grab_focus()
Gtk.main()
